### ISSUE TITLE
1.21.4 Purpur 无法加载插件

### ISSUE THREAD

**Issue by luckeist** [4o4E/Boom#10]
[08:26:47 INFO]: [Boom] Enabling Boom v2.11.0
[08:26:47 ERROR]: Error occurred while enabling Boom v2.11.0 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at Boom-2.11.0.jar/top.e404.eplugin.util.SoundConfig$$serializer.deserialize(config.kt:26) ~[Boom-2.11.0.jar:?]
        at Boom-2.11.0.jar/top.e404.eplugin.util.SoundConfig$$serializer.deserialize(config.kt:26) ~[Boom-2.11.0.jar:?]
        at Boom-2.11.0.jar/top.e404.boom.relocate.kotlinx.serialization.encoding.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:257) ~[Boom-2.11.0.jar:?]
        at Boom-2.11.0.jar/top.e404.boom.relocate.kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:16) ~[Boom-2.11.0.jar:?]
        at Boom-2.11.0.jar/com.charleskorn.kaml.YamlInput.decodeSerializableValue(YamlInput.kt:104) ~[Boom-2.11.0.jar:?]
        at Boom-2.11.0.jar/top.e404.boom.relocate.kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43) ~[Boom-2.11.0.jar:?]
        at Boom-2.11.0.jar/top.e404.boom.relocate.kotlinx.serialization.encoding.AbstractDecoder.decodeNullableSerializableElement(AbstractDecoder.kt:79) ~[Boom-2.11.0.jar:?]
        at Boom-2.11.0.jar/top.e404.boom.config.PreventUseConfig$$serializer.deserialize(Config.kt:154) ~[Boom-2.11.0.jar:?]
        at Boom-2.11.0.jar/top.e404.boom.config.PreventUseConfig$$serializer.deserialize(Config.kt:154) ~[Boom-2.11.0.jar:?]
        at Boom-2.11.0.jar/top.e404.boom.relocate.kotlinx.serialization.encoding.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:257) ~[Boom-2.11.0.jar:?]
        at Boom-2.11.0.jar/top.e404.boom.relocate.kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:16) ~[Boom-2.11.0.jar:?]
        at Boom-2.11.0.jar/com.charleskorn.kaml.YamlInput.decodeSerializableValue(YamlInput.kt:104) ~[Boom-2.11.0.jar:?]
        at Boom-2.11.0.jar/top.e404.boom.relocate.kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43) ~[Boom-2.11.0.jar:?]
        at Boom-2.11.0.jar/top.e404.boom.relocate.kotlinx.serialization.encoding.AbstractDecoder.decodeNullableSerializableElement(AbstractDecoder.kt:79) ~[Boom-2.11.0.jar:?]
        at Boom-2.11.0.jar/top.e404.boom.config.BoomConfig$$serializer.deserialize(Config.kt:90) ~[Boom-2.11.0.jar:?]
        at Boom-2.11.0.jar/top.e404.boom.config.BoomConfig$$serializer.deserialize(Config.kt:90) ~[Boom-2.11.0.jar:?]
        at Boom-2.11.0.jar/top.e404.boom.relocate.kotlinx.serialization.encoding.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:257) ~[Boom-2.11.0.jar:?]
        at Boom-2.11.0.jar/top.e404.boom.relocate.kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:16) ~[Boom-2.11.0.jar:?]
        at Boom-2.11.0.jar/com.charleskorn.kaml.YamlInput.decodeSerializableValue(YamlInput.kt:104) ~[Boom-2.11.0.jar:?]
        at Boom-2.11.0.jar/top.e404.boom.relocate.kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43) ~[Boom-2.11.0.jar:?]
        at Boom-2.11.0.jar/top.e404.boom.relocate.kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70) ~[Boom-2.11.0.jar:?]
        at Boom-2.11.0.jar/top.e404.boom.config.RgConfig$$serializer.deserialize(Config.kt:56) ~[Boom-2.11.0.jar:?]
        at Boom-2.11.0.jar/top.e404.boom.config.RgConfig$$serializer.deserialize(Config.kt:56) ~[Boom-2.11.0.jar:?]
        at Boom-2.11.0.jar/top.e404.boom.relocate.kotlinx.serialization.encoding.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:257) ~[Boom-2.11.0.jar:?]
        at Boom-2.11.0.jar/top.e404.boom.relocate.kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:16) ~[Boom-2.11.0.jar:?]
        at Boom-2.11.0.jar/com.charleskorn.kaml.YamlInput.decodeSerializableValue(YamlInput.kt:104) ~[Boom-2.11.0.jar:?]
        at Boom-2.11.0.jar/com.charleskorn.kaml.Yaml.decodeFromReader(Yaml.kt:54) ~[Boom-2.11.0.jar:?]
        at Boom-2.11.0.jar/com.charleskorn.kaml.Yaml.decodeFromString(Yaml.kt:43) ~[Boom-2.11.0.jar:?]
        at Boom-2.11.0.jar/top.e404.eplugin.config.KtxConfig.load(KtxConfig.kt:72) ~[Boom-2.11.0.jar:?]
        at Boom-2.11.0.jar/top.e404.boom.Boom.onEnable(Boom.kt:41) ~[Boom-2.11.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[purpur-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.21.4.jar:1.21.4-2365-80b6d34]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.4.jar:1.21.4-2365-80b6d34]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[purpur-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:669) ~[purpur-1.21.4.jar:1.21.4-2365-80b6d34]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:618) ~[purpur-1.21.4.jar:1.21.4-2365-80b6d34]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:773) ~[purpur-1.21.4.jar:1.21.4-2365-80b6d34]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:535) ~[purpur-1.21.4.jar:1.21.4-2365-80b6d34]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:363) ~[purpur-1.21.4.jar:1.21.4-2365-80b6d34]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1252) ~[purpur-1.21.4.jar:1.21.4-2365-80b6d34]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:345) ~[purpur-1.21.4.jar:1.21.4-2365-80b6d34]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassCastException: class [Lorg.bukkit.Sound; cannot be cast to class [Ljava.lang.Enum; ([Lorg.bukkit.Sound; is in unnamed module of loader java.net.URLClassLoader @2ef1e4fa; [Ljava.lang.Enum; is in module java.base of loader 'bootstrap')
        at Boom-2.11.0.jar/top.e404.eplugin.util.SoundConfig.<clinit>(config.kt:26) ~[Boom-2.11.0.jar:?]
        ... 42 more
[08:26:47 INFO]: [Boom] Disabling Boom v2.11.0
[08:26:47 INFO]: [Boom] 卸载完成, 作者404E, 感谢使用

**Comment by 4o4E** [comment]
删除配置文件重新生成

**Comment by luckeist** [comment]
> 删除配置文件重新生成

试过了故障依旧

**Comment by Chaostarts** [comment]
> 删除配置文件重新生成

同样 1.21.4无法使用此插件

**Comment by 4o4E** [comment]
https://github.com/4o4E/Boom/releases/tag/2.12.0
