### ISSUE TITLE
1.19.0purpur无法加载插件

### ISSUE THREAD

**Issue by AUndead** [4o4E/Boom#4]
报错:
[18:43:55 INFO]: [Boom] Enabling Boom v2.0.8
[18:43:55 ERROR]: Error occurred while enabling Boom v2.0.8 (Is it up to date?)
java.lang.NullPointerException: null
        at top.e404.boom.config.Config.onLoad(Config.kt:40) ~[[B-防爆]Boom-2.0.8.jar:?]
        at top.e404.eplugin.config.EConfig.load(EConfig.kt:75) ~[[B-防爆]Boom-2.0.8.jar:?]
        at top.e404.boom.Boom.onEnable(Boom.kt:33) ~[[B-防爆]Boom-2.0.8.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:594) ~[purpur-1.19.jar:git-Purpur-1708]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:508) ~[purpur-1.19.jar:git-Purpur-1708]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638) ~[purpur-1.19.jar:git-Purpur-1708]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[purpur-1.19.jar:git-Purpur-1708]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:342) ~[purpur-1.19.jar:git-Purpur-1708]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1137) ~[purpur-1.19.jar:git-Purpur-1708]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[purpur-1.19.jar:git-Purpur-1708]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[18:43:55 INFO]: [Boom] Disabling Boom v2.0.8
[18:43:55 INFO]: [Boom] 卸载完成, 作者404E, 感谢使用

**Comment by 4o4E** [comment]
更新后请删除配置文件重新生成

**Comment by AUndead** [comment]
好的,感谢！
